application: perfectroommateversion5
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts


- url: /get_channel_token
  script: channel_server.app

- url: /opened
  script: channel_server.app

- url: /opened_from_management
  script: chat_server.app

- url: /get_chat_channel_token
  script: chat_server.app

- url: /newMessage
  script: chat_server.app

- url: /retrieve_Dialog_history
  script: chat_server_helper.app

- url: /get_unread_candidates
  script: chat_server_helper.app

- url: /setMyUnreadToFalse
  script: chat_server_helper.app

- url: /check_unread_message
  script: chat_server_helper.app


- url: /personal_info_handler
  script:  personal_info_handler.app

- url: /personal_preference_handler
  script: personal_preference_handler.app

- url: /management
  script: management.app

- url: /my_pref_setting
  script: set_preference.app

- url: /chatroom
  script: chatroom.app

- url: /matchmanagement
  script: matchmanagement.app

- url: /high_light_matches
  script: match_page_helper.app

- url: /changeoptionsonright
  script: match_page_helper.app

- url: /potentialroommate_management
  script: potentialroommate_management.app

- url: /addpotentialpersons
  script: potentialmatch_management.app

- url: /deletepotentialpersons
  script: potentialroommate_management.app

- url: /popup_about
  script: popuphandler.app

- url: /popup_help
  script: popuphandler.app

- url: /popup_report_issue
  script: popuphandler.app

- url: /send_usr_report_issue
  script: email_engine.app

- url: /
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
